export function getNationCodeName(code: string): string | undefined {
    switch (code) {
        case "HK":
            return "中国香港";
        case "TW":
            return "中国台湾";
        case "CN":
            return "中国";
        case "MO":
            return "中国澳门";
        case "CF":
            return "中非共和国";
        case "CL":
            return "智利";
        case "GI":
            return "直布罗陀";
        case "TD":
            return "乍得";
        case "ZM":
            return "赞比亚";
        case "VN":
            return "越南";
        case "JO":
            return "约旦";
        case "VG":
            return "维尔京群岛（英属）";// 文档：英属维尔京群岛 
        case "GB":
            return "英国";
        case "ID":
            return "印度尼西亚";
        case "IN":
            return "印度";
        case "IT":
            return "意大利";
        case "IL":
            return "以色列";
        case "IR":
            return "伊朗";
        case "IQ":
            return "伊拉克";
        case "YE":
            return "也门共和国"; // 文档：也门共和国也称也门    
        case "AM":
            return "亚美尼亚";
        case "JM":
            return "牙买加";
        case "SY":
            return "叙利亚";
        case "HU":
            return "匈牙利";
        case "NZ":
            return "新西兰";
        case "NC":
            return "新喀里多尼亚群岛";
        case "SG":
            return "新加坡";
        case "GR":
            return "希腊";
        case "ES":
            return "西班牙";
        case "UZ":
            return "乌兹别克斯坦";
        case "UY":
            return "乌拉圭";
        case "UA":
            return "乌克兰";
        case "UG":
            return "乌干达";
        case "BN":
            return "文莱达鲁萨兰国";
        case "VE":
            return "委内瑞拉";
        case "GT":
            return "危地马拉";
        case "VU":
            return "瓦努阿图";
        case "WF":
            return "瓦利斯和富图纳群岛";
        case "TK":
            return "托克劳";
        case "TM":
            return "土库曼斯坦";
        case "TR":
            return "土耳其";
        case "TV":
            return "图瓦卢";
        case "TN":
            return "突尼斯";
        case "TT":
            return "特立尼达和多巴哥";
        case "TC":
            return "特克斯和凯科斯群岛";
        case "TO":
            return "汤加";
        case "TZ":
            return "坦桑尼亚";
        case "TH":
            return "泰国";
        case "TJ":
            return "塔吉克斯坦";
        case "SO":
            return "索马里";
        case "SB":
            return "所罗门群岛";
        case "SR":
            return "苏里南";
        case "SD":
            return "苏丹";
        case "SZ":
            return "斯威士兰";
        // case "SJ":
        //     return "斯瓦尔巴岛和扬马延岛(挪)";
        case "SI":
            return "斯洛文尼亚";
        case "SK":
            return "斯洛伐克共和国";
        case "LK":
            return "斯里兰卡";
        case "VC":
            return "圣文森特和格林纳丁斯";
        case "SM":
            return "圣马力诺";
        case "LC":
            return "圣卢西亚";
        case "KN":
            return "圣基茨和尼维斯";
        // case "SH":
        //     return "圣赫勒拿(英)";
        case "ST":
            return "圣多美和普林西比";
        case "CX":
            return "圣诞岛(澳)";
        case "SA":
            return "沙特阿拉伯";
        case "SC":
            return "塞舌尔";
        case "CY":
            return "塞浦路斯";
        case "SN":
            return "塞内加尔";
        case "SL":
            return "塞拉利昂";
        case "CS":
            return "塞尔维亚";
        case "WS":
            return "萨摩亚群岛"; // 文档：萨摩亚
        case "SV":
            return "萨尔瓦多";
        case "CH":
            return "瑞士";
        case "SE":
            return "瑞典";
        case "JP":
            return "日本";
        case "PM":
            return "圣皮埃尔和密克隆";
        case "PT":
            return "葡萄牙";
        case "PW":
            return "帕劳";
        case "NF":
            return "诺福克岛";
        case "NO":
            return "挪威";
        case "NU":
            return "纽埃";
        case "NG":
            return "尼日利亚";
        case "NE":
            return "尼日尔";
        case "NP":
            return "尼泊尔";
        case "NI":
            return "尼加拉瓜";
        case "NR":
            return "瑙鲁";
        case "ZA":
            return "南非";
        case "NA":
            return "纳米比亚";
        case "MX":
            return "墨西哥";
        case "MZ":
            return "莫桑比克";
        case "MC":
            return "摩纳哥"
        case "MA":
            return "摩洛哥";
        case "MD":
            return "摩尔多瓦";
        case "MM":
            return "缅甸";
        case "FM":
            return "密克罗尼西亚联邦";
        case "PE":
            return "秘鲁";
        case "BD":
            return "孟加拉国";
        case "MS":
            return "蒙特赛拉特岛";// 文档：蒙特塞拉特，南航：蒙特赛拉特岛
        case "MN":
            return "蒙古";
        case "VI":
            return "维尔京群岛（美属）";// 文档：美属维尔京群岛
        case "AS":
            return "美属萨摩亚";
        case "UM":
            return "美国本土外小岛屿(美)";
        case "US":
            return "美国";
        case "MR":
            return "毛利塔尼亚"; // 文档：毛里塔尼亚，南航：毛利塔尼亚
        case "MU":
            return "毛里求斯"; // 毛里求斯又叫毛里求斯共和国
        case "YT":
            return "马约特岛"; // 文档：马约特，南航：马约特岛
        case "MQ":
            return "马提尼克";
        case "MH":
            return "马绍尔群岛";
        case "MK":
            return "马其顿";
        case "ML":
            return "马里";
        case "MY":
            return "马来西亚";
        case "MW":
            return "马拉维";
        case "MT":
            return "马耳他";
        case "MV":
            return "马尔代夫";
        case "MG":
            return "马达加斯加";
        case "RO":
            return "罗马尼亚";
        case "RW":
            return "卢旺达";
        case "LU":
            return "卢森堡";
        case "RE":
            return "留尼旺岛";// 文档：留尼汪
        case "LI":
            return "列支敦士登";
        case "LY":
            return "利比亚";
        case "LR":
            return "利比里亚";
        case "LT":
            return "立陶宛";
        case "LB":
            return "黎巴嫩";
        case "LA":
            return "老挝";
        case "LS":
            return "莱索托";
        case "LV":
            return "拉脱维亚";
        case "CK":
            return "库克群岛";
        case "KE":
            return "肯尼亚";
        case "HR":
            return "克罗地亚";
        case "KW":
            return "科威特";
        case "CI":
            return "科特迪瓦";
        case "KM":
            return "科摩罗";
        case "CC":
            return "科科斯群岛(澳)";
        case "KY":
            return "开曼群岛(英)";
        case "QA":
            return "卡塔尔";
        case "CM":
            return "喀麦隆";
        case "ZW":
            return "津巴布韦";
        case "CZ":
            return "捷克共和国";
        case "KH":
            return "柬埔寨";
        case "GA":
            return "加蓬";
        case "GH":
            return "加纳";
        case "CA":
            return "加拿大";
        case "GW":
            return "几内亚比绍";
        case "GN":
            return "几内亚";
        case "KG":
            return "吉尔吉斯斯坦"; // 吉尔吉斯斯坦也叫吉尔吉斯共和国
        case "DJ":
            return "吉布提";
        case "KI":
            return "基里巴斯";
        case "HN":
            return "洪都拉斯";
        case "HM":
            return "赫德岛和麦克唐纳岛(澳)";
        case "AN":
            return "荷属安的列斯(荷)";
        case "NL":
            return "荷兰";
        case "KR":
            return "韩国";
        case "GB":
            return "海峡群岛(英)";
        case "HT":
            return "海地";
        case "KZ":
            return "哈萨克斯坦";
        case "GY":
            return "圭亚那";
        case "GU":
            return "关岛（马里亚纳群岛）"; // 文档：关岛
        case "GP":
            return "瓜德罗普岛(法)";
        case "CU":
            return "古巴共和国";
        case "GE":
            return "格鲁吉亚";
        case "GL":
            return "格陵兰(丹)";
        case "GD":
            return "格林纳达";
        case "CR":
            return "哥斯达里加"; // 文档：哥斯达黎加
        case "CO":
            return "哥伦比亚";
        case "CD":
            return "刚果(金沙萨)";
        case "CG":
            return "刚果（布）";
        case "GM":
            return "冈比亚";
        case "FK":
            return "福克兰群岛";
        case "CV":
            return "佛得角";
        case "FI":
            return "芬兰";
        case "FJ":
            return "斐济";
        case "PH":
            return "菲律宾";
        case "VA":
            return "梵蒂冈";
        case "GF":
            return "法属圭亚那";
        case "PF":
            return "法属波利尼西亚";
        case "FO":
            return "法罗群岛";
        case "FR":
            return "法国";
        case "ER":
            return "厄立特里亚";
        case "EC":
            return "厄瓜多尔";
        case "RU":
            return "俄罗斯联邦";
        case "DM":
            return "多米尼克";
        case "DO":
            return "多米尼加共和国";
        case "TG":
            return "多哥";
        case "TL":
            return "东帝汶";
        case "DE":
            return "德国";
        case "DK":
            return "丹麦";
        case "GQ":
            return "赤道几内亚";
        case "KP":
            return "朝鲜民主主义共和国"; // 朝鲜
        case "BV":
            return "布韦岛";
        case "BI":
            return "布隆迪";
        case "BF":
            return "布基纳法索";
        case "BT":
            return "不丹";
        case "BW":
            return "博茨瓦纳";
        case "BZ":
            return "伯里兹";
        case "BO":
            return "玻利维亚";
        case "BA":
            return "波斯尼亚和黑塞哥维那";
        case "PL":
            return "波兰";
        case "PR":
            return "波多黎各";
        case "IS":
            return "冰岛";
        case "BE":
            return "比利时";
        case "BJ":
            return "贝宁";
        case "MP":
            return "北马里亚纳群岛"; // 文档：北马里亚纳
        case "BG":
            return "保加利亚";
        case "BM":
            return "百慕大群岛";
        case "BY":
            return "白俄罗斯";
        case "BR":
            return "巴西";
        case "PA":
            return "巴拿马";
        case "BH":
            return "巴林";
        case "PS":
            return "巴勒斯坦被占地区";
        case "PY":
            return "巴拉圭";
        case "PK":
            return "巴基斯坦";
        case "BS":
            return "巴哈马";
        case "PG":
            return "巴布亚新几内亚";
        case "BB":
            return "巴巴多斯";
        case "AU":
            return "澳大利亚";
        case "AT":
            return "奥地利";
        case "AG":
            return "安提瓜和巴布达";
        case "AI":
            return "安圭拉";
        case "AO":
            return "安哥拉";
        case "AD":
            return "安道尔";
        case "EE":
            return "爱沙尼亚";
        case "IE":
            return "爱尔兰";
        case "ET":
            return "埃塞俄比亚";
        case "EG":
            return "埃及";
        case "AZ":
            return "阿塞拜疆共和国";
        case "OM":
            return "阿曼";
        case "AW":
            return "阿鲁巴(荷)";
        case "AE":
            return "阿拉伯联合酋长国";
        case "AR":
            return "阿根廷";
        case "AF":
            return "阿富汗";
        case "DZ":
            return "阿尔及利亚";
        case "AL":
            return "阿尔巴尼亚";
        case "ZR":
            return "扎伊尔";
    }
}