export function getCityName(airport: string): string | undefined {
    switch (airport) {
        case "SHE":
            return "沈阳";
        case "LNL":
            return "陇南";
        case "DTU":
            return "五大连池";
        case "WSK":
            return "巫山";
        case "AHJ":
            return "合肥";
        case "RQA":
            return "若羌";
        case "JSJ":
            return "佳木斯";
        case "BZX":
            return "巴中";
        case "HSC":
            return "韶关";
        case "XRQ":
            return "新巴尔虎右旗";
        case "YYA":
            return "岳阳";
        case "LFQ":
            return "临汾";
        case "SQJ":
            return "三明";
        case "JIC":
            return "金昌";
        case "YTW":
            return "于田县";
        case "WHA":
            return "芜湖";
        case "TFU":
            return "成都";
        case "DZH":
            return "达州";
        case "HLD":
            return "呼伦贝尔";
        case "SQD":
            return "上饶";
        case "WZQ":
            return "乌拉特中旗";
        case "RHT":
            return "阿拉善右旗";
        case "ROQ":
            return "阿荣旗";
        case "TYC":
            return "太原";
        case "LZO":
            return "泸州";
        case "NBS":
            return "长白山";
        case "NLH":
            return "宁蒗";
        case "YBP":
            return "宜宾";
        case "XMN":
            return "厦门";
        case "WUZ":
            return "梧州";
        case "HPG":
            return "神农架";
        case "NNY":
            return "南阳";
        case "LYA":
            return "洛阳";
        case "WUH":
            return "武汉";
        case "ENH":
            return "恩施";
        case "CGO":
            return "郑州";
        case "AYN":
            return "安阳";
        case "ZHA":
            return "湛江";
        case "LZH":
            return "柳州";
        case "XIN":
            return "兴宁";
        case "SZX":
            return "深圳";
        case "WGN":
            return "邵阳";
        case "ZUH":
            return "珠海";
        case "SWA":
            return "揭阳";
        case "NNG":
            return "南宁";
        case "MXZ":
            return "梅州";
        case "NZL":
            return "扎兰屯";
        case "BHY":
            return "北海";
        case "CGD":
            return "常德";
        case "HJJ":
            return "怀化";
        case "SHS":
            return "荆州";
        case "DYG":
            return "张家界";
        case "CSX":
            return "长沙";
        case "HCJ":
            return "河池";
        case "SHF":
            return "石河子";
        case "HNY":
            return "衡阳";
        case "KWL":
            return "桂林";
        case "LLF":
            return "永州";
        case "CAN":
            return "广州";
        case "WDS":
            return "十堰";
        case "XFN":
            return "襄阳";
        case "YIH":
            return "宜昌";
        case "LHW":
            return "兰州";
        case "IQN":
            return "庆阳";
        case "SIA":
            return "西安";
        case "GXH":
            return "甘肃夏河";
        case "XNN":
            return "西宁";
        case "JGN":
            return "嘉峪关";
        case "XIY":
            return "西安";
        case "ZHY":
            return "中卫";
        case "UYN":
            return "榆林";
        case "RLK":
            return "巴彦淖尔";
        case "JNG":
            return "济宁";
        case "HZG":
            return "汉中";
        case "HAK":
            return "海口";
        case "BAR":
            return "琼海";
        case "SYX":
            return "三亚";
        case "INC":
            return "银川";
        case "DNH":
            return "敦煌";
        case "HXD":
            return "德令哈";
        case "GOQ":
            return "格尔木";
        case "GYU":
            return "固原";
        case "HTT":
            return "花土沟";
        case "AKA":
            return "安康";
        case "TYN":
            return "太原";
        case "WUT":
            return "五台山";
        case "LLV":
            return "吕梁";
        case "NZH":
            return "满洲里";
        case "NAY":
            return "北京";
        case "BAV":
            return "包头";
        case "SJW":
            return "石家庄";
        case "TGO":
            return "通辽";
        case "UCB":
            return "乌兰察布";
        case "WUA":
            return "乌海";
        case "HLH":
            return "乌兰浩特";
        case "XIL":
            return "锡林浩特";
        case "XNT":
            return "邢台";
        case "TSN":
            return "天津";
        case "YCU":
            return "运城";
        case "HUO":
            return "霍林郭勒";
        case "HDG":
            return "邯郸";
        case "PEK":
            return "北京首都";
        case "PKX":
            return "北京大兴";
        case "HET":
            return "呼和浩特";
        case "CDE":
            return "承德";
        case "CIH":
            return "长治";
        case "BPE":
            return "秦皇岛";
        case "DSN":
            return "鄂尔多斯";
        case "DAT":
            return "大同";
        case "ERL":
            return "二连浩特";
        case "YIE":
            return "阿尔山";
        case "CIF":
            return "赤峰";
        case "KRL":
            return "库尔勒";
        case "KCA":
            return "库车";
        case "HMI":
            return "哈密";
        case "FYN":
            return "富蕴";
        case "IQM":
            return "且末";
        case "BPL":
            return "博乐";
        case "AKU":
            return "阿克苏";
        case "ZYI":
            return "遵义";
        case "ACX":
            return "兴义";
        case "XIC":
            return "西昌";
        case "WXN":
            return "万州";
        case "CTU":
            return "成都";
        case "TEN":
            return "铜仁";
        case "TCZ":
            return "腾冲";
        case "LPF":
            return "六盘水";
        case "LZY":
            return "林芝";
        case "GYS":
            return "广元";
        case "KWE":
            return "贵阳";
        case "GZG":
            return "甘孜";
        case "JZH":
            return "九寨沟";
        case "KGT":
            return "康定";
        case "KJH":
            return "凯里";
        case "KRY":
            return "克拉玛依";
        case "LLB":
            return "荔波";
        case "LXA":
            return "拉萨";
        case "WMT":
            return "遵义茅台";
        case "MIG":
            return "绵阳";
        case "NAO":
            return "南充";
        case "HZH":
            return "黎平";
        case "LIA":
            return "梁平";
        case "KJI":
            return "喀纳斯";
        case "NLT":
            return "那拉提";
        case "JXA":
            return "鸡西";
        case "JNZ":
            return "锦州";
        case "LDS":
            return "伊春";
        case "YUS":
            return "玉树";
        case "MDG":
            return "牡丹江";
        case "JMU":
            return "佳木斯";
        case "OHE":
            return "漠河";
        case "DLC":
            return "大连";
        case "TNH":
            return "通化";
        case "SHE":
            return "沈阳";
        case "YNJ":
            return "延吉";
        case "YKH":
            return "营口";
        case "NDG":
            return "齐齐哈尔";
        case "GHN":
            return "广汉";
        case "JIL":
            return "吉林";
        case "HRB":
            return "哈尔滨";
        case "QSZ":
            return "莎车";
        case "KHG":
            return "喀什";
        case "SXJ":
            return "膳善";
        case "TCG":
            return "塔城";
        case "HTN":
            return "和田";
        case "TLQ":
            return "吐鲁番";
        case "HEK":
            return "黑河";
        case "URC":
            return "乌鲁木齐";
        case "AOG":
            return "鞍山";
        case "CGQ":
            return "长春";
        case "CNI":
            return "长海";
        case "CHG":
            return "朝阳";
        case "FYJ":
            return "抚远";
        case "YIN":
            return "伊宁";
        case "DAX":
            return "达州";
        case "DCY":
            return "稻城";
        case "CKG":
            return "重庆";
        case "JMJ":
            return "澜沧";
        case "LJG":
            return "丽江";
        case "LUM":
            return "芒市";
        case "KMG":
            return "昆明";
        case "SYM":
            return "普洱";
        case "WNH":
            return "文山";
        case "JHG":
            return "西双版纳";
        case "ZAT":
            return "昭通";
        case "BFU":
            return "蚌埠";
        case "CZX":
            return "常州";
        case "KHN":
            return "南昌";
        case "FUG":
            return "阜阳";
        case "FOC":
            return "福州";
        case "KOW":
            return "赣州";
        case "AQG":
            return "安庆";
        case "HGH":
            return "杭州";
        case "DIG":
            return "迪庆";
        case "CWJ":
            return "沧源";
        case "DLU":
            return "大理";
        case "JDZ":
            return "景德镇";
        case "TNA":
            return "济南";
        case "WHU":
            return "芜湖";
        case "WUX":
            return "无锡";
        case "WUS":
            return "武夷山";
        case "WNZ":
            return "温州";
        case "XUZ":
            return "徐州";
        case "YTY":
            return "扬州";
        case "WEH":
            return "威海";
        case "YIC":
            return "宜春";
        case "YIW":
            return "义乌";
        case "HSN":
            return "舟山";
        case "NGQ":
            return "阿里";
        case "AVA":
            return "安顺";
        case "BPX":
            return "昌都邦达";
        case "BFJ":
            return "毕节";
        case "YNZ":
            return "盐城";
        case "JIU":
            return "九江";
        case "WEF":
            return "潍坊";
        case "SZV":
            return "苏州";
        case "JUZ":
            return "衢州";
        case "LCX":
            return "连城";
        case "LYG":
            return "连云港";
        case "HYN":
            return "台州";
        case "LYI":
            return "临沂";
        case "NGB":
            return "宁波";
        case "TXN":
            return "黄山";
        case "NKG":
            return "南京";
        case "PVG":
            return "上海浦东";
        case "TAO":
            return "青岛";
        case "JJN":
            return "晋江";
        case "RUG":
            return "如皋";
        case "RIZ":
            return "日照";
        case "SHA":
            return "上海虹桥";
        case "HFE":
            return "合肥";
        case "TWC":
            return "图木舒克";
        case "EJN":
            return "额济纳";
        case "ENY":
            return "延安";
        case "DQA":
            return "大庆";
        case "GMQ":
            return "果洛";
        case "AEQ":
            return "赤峰";
        case "AXF":
            return "阿拉善左旗";
        case "DBC":
            return "白城";
        case "DEQ":
            return "莫干山";
        case "NTG":
            return "南通";
        case "DDG":
            return "丹东";
        case "THQ":
            return "天水";
        case "LNJ":
            return "临沧";
        case "RKZ":
            return "日喀则";
        case "PZI":
            return "攀枝花";
        case "ZKL":
            return "自贡";
        case "FUO":
            return "佛山";
        case "DZU":
            return "大足";
        case "XAI":
            return "信阳";
        case "JGS":
            return "井冈山";
        case "AEB":
            return "百色田阳";
        case "DOY":
            return "东营";
        case "XEN":
            return "兴城";
        case "AAT":
            return "阿勒泰";
        case "HUZ":
            return "惠州";
        case "YZY":
            return "张掖";
        case "BSD":
            return "保山";
        case "YUA":
            return "元谋";
        case "ZQZ":
            return "张家口";
        case "TVS":
            return "唐山";
        case "YNT":
            return "烟台";
        case "XHQ":
            return "镶黄旗";
        case "YLX":
            return "玉林";
        case "JIQ":
            return "黔江";
        case "JGD":
            return "加格达奇";
        case "JUH":
            return "池州";
        case "HBQ":
            return "祁连";
        case "HSJ":
            return "上街";
        case "HIA":
            return "淮安";
        case "YSQ":
            return "松原市";
        case "YUN":
            return "密云";
        case "AZJ":
            return "镇江";
        case "CBZ":
            return "滨州";
        case "CQW":
            return "重庆市武隆区";
        case "DFA":
            return "丹凤";
        case "DXQ":
            return "儋州";
        case "EQQ":
            return "鄂托克前旗";
        case "HZY":
            return "华彬庄园";
        case "JDE":
            return "建德";
        case "LCS":
            return "陇川";
        case "LCT":
            return "石家庄";
        case "LFH":
            return "兰坪";
        case "LZL":
            return "珠海";
        case "NJJ":
            return "嫩江";
        default:
            return undefined;
    }
}
